// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
<<<<<<<< HEAD:Infrastructure/Migrations/20260822153346_Initial.Designer.cs
    [Migration("20260822153346_Initial")]
    partial class Initial
========
    [Migration("20260820202713_Change Account Table")]
    partial class ChangeAccountTable
>>>>>>>> AshrafB:Infrastructure/Migrations/20260820202713_Change Account Table.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

<<<<<<<< HEAD:Infrastructure/Migrations/20260822153346_Initial.Designer.cs
                    b.Property<int>("Gender")
                        .HasColumnType("int");
========
                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("char(1)");
>>>>>>>> AshrafB:Infrastructure/Migrations/20260820202713_Change Account Table.Designer.cs

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndAt")
                        .HasColumnType("date");

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("varchar");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProjectManagerId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProjectEmployee", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
<<<<<<<< HEAD:Infrastructure/Migrations/20260822153346_Initial.Designer.cs
                        .HasColumnType("nvarchar(max)");
========
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
>>>>>>>> AshrafB:Infrastructure/Migrations/20260820202713_Change Account Table.Designer.cs

                    b.HasKey("ProjectId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ProjectEmployees", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

<<<<<<<< HEAD:Infrastructure/Migrations/20260822153346_Initial.Designer.cs
                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("DATE");
========
                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");
>>>>>>>> AshrafB:Infrastructure/Migrations/20260820202713_Change Account Table.Designer.cs

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar");

<<<<<<<< HEAD:Infrastructure/Migrations/20260822153346_Initial.Designer.cs
                    b.Property<DateOnly?>("DueTo")
                        .HasColumnType("DATE");
========
                    b.Property<DateTime?>("DueTo")
                        .HasColumnType("datetime");
>>>>>>>> AshrafB:Infrastructure/Migrations/20260820202713_Change Account Table.Designer.cs

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TicketCreatedById")
                        .HasColumnType("int");

                    b.Property<string>("TicketStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketTitle")
                        .IsRequired()
<<<<<<<< HEAD:Infrastructure/Migrations/20260822153346_Initial.Designer.cs
                        .HasMaxLength(20)
========
                        .HasMaxLength(100)
>>>>>>>> AshrafB:Infrastructure/Migrations/20260820202713_Change Account Table.Designer.cs
                        .HasColumnType("varchar");

                    b.HasKey("TicketId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TicketCreatedById");

                    b.ToTable("Tickets", (string)null);
                });

<<<<<<<< HEAD:Infrastructure/Migrations/20260822153346_Initial.Designer.cs
            modelBuilder.Entity("Domain.Entities.TicketAttachments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Attachments", (string)null);
                });

========
>>>>>>>> AshrafB:Infrastructure/Migrations/20260820202713_Change Account Table.Designer.cs
            modelBuilder.Entity("Domain.Entities.TicketHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
<<<<<<<< HEAD:Infrastructure/Migrations/20260822153346_Initial.Designer.cs
                        .HasColumnType("nvarchar(max)");
========
                        .HasMaxLength(100)
                        .HasColumnType("varchar");
>>>>>>>> AshrafB:Infrastructure/Migrations/20260820202713_Change Account Table.Designer.cs

                    b.Property<int>("ActionByEmployeeId")
                        .HasColumnType("int");

<<<<<<<< HEAD:Infrastructure/Migrations/20260822153346_Initial.Designer.cs
                    b.Property<int?>("FromEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");
========
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("FromEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar");
>>>>>>>> AshrafB:Infrastructure/Migrations/20260820202713_Change Account Table.Designer.cs

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int?>("ToEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionByEmployeeId");

                    b.HasIndex("FromEmployeeId");

                    b.HasIndex("TicketId");

                    b.HasIndex("ToEmployeeId");

<<<<<<<< HEAD:Infrastructure/Migrations/20260822153346_Initial.Designer.cs
                    b.ToTable("TicketHistories");
========
                    b.ToTable("TicketHistories", (string)null);
>>>>>>>> AshrafB:Infrastructure/Migrations/20260820202713_Change Account Table.Designer.cs
                });

            modelBuilder.Entity("Account", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("Account", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("Domain.Entities.ProjectEmployee", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("Tickets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("ProjectTickets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", "TicketCreatedBy")
                        .WithMany()
                        .HasForeignKey("TicketCreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");

                    b.Navigation("TicketCreatedBy");
                });

<<<<<<<< HEAD:Infrastructure/Migrations/20260822153346_Initial.Designer.cs
            modelBuilder.Entity("Domain.Entities.TicketAttachments", b =>
                {
                    b.HasOne("Domain.Entities.Ticket", "Ticket")
                        .WithMany("AttachmentURL")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Domain.Entities.TicketHistory", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "ActionByEmployee")
                        .WithMany()
                        .HasForeignKey("ActionByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", "FromEmployee")
                        .WithMany()
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketHistories")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", "ToEmployee")
                        .WithMany("TicketHistories")
                        .HasForeignKey("ToEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ActionByEmployee");

                    b.Navigation("FromEmployee");

                    b.Navigation("Ticket");

                    b.Navigation("ToEmployee");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
========
            modelBuilder.Entity("Domain.Entities.TicketHistory", b =>
>>>>>>>> AshrafB:Infrastructure/Migrations/20260820202713_Change Account Table.Designer.cs
                {
                    b.HasOne("Domain.Entities.Employee", "ActionByEmployee")
                        .WithMany("TicketHistories")
                        .HasForeignKey("ActionByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", "FromEmployee")
                        .WithMany()
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketHistories")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", "ToEmployee")
                        .WithMany()
                        .HasForeignKey("ToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActionByEmployee");

                    b.Navigation("FromEmployee");

                    b.Navigation("Ticket");

                    b.Navigation("ToEmployee");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("ProjectEmployees");

                    b.Navigation("TicketHistories");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectEmployees");

                    b.Navigation("ProjectTickets");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
<<<<<<<< HEAD:Infrastructure/Migrations/20260822153346_Initial.Designer.cs
                    b.Navigation("AttachmentURL");

========
>>>>>>>> AshrafB:Infrastructure/Migrations/20260820202713_Change Account Table.Designer.cs
                    b.Navigation("TicketHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
