namespace ApplicationServices.DTOs.Account
{
    public class SignUpRequest
    {
        public string Email { get; set; } = null!;

        public string Password { get; set; } = null!;

        public int EmployeeId { get; set; } // ? generated by database
    }
}